name:                DecisionTheory
version:             0.1.0.0
github:              "DecisionTheory/DecisionTheory"
license:             Apache-2.0
author:              "Daniel Yokomizo & Gustavo Bicalho"
maintainer:          "daniel.yokomizo@gmail.com"
# copyright:

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Decision Theory implementations in Haskell
category:            Math

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  DecisionTheory-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - QuickCheck
    - DecisionTheory
